version: "3"
services:
  tgbot:
    build: src/main/tgbot
    ports:
      - "1234:1234"
      -
    environment:
      - TELEGRAM_TOKEN=secret1
      - SECRET_KEY_BASE=secret2
      - MONGO_URL=mongodb://mongo:27017/app_development
  mongo:
    ports:
      - "27017:27017"